services:
  node-job:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cronjob-current-program
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    environment:
      - NODE_ENV=production
